# Generated by Django 3.1.3 on 2020-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201115_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('start', models.TimeField(verbose_name='início')),
                ('description', models.TextField(verbose_name='descrição')),
                ('speakers', models.ManyToManyField(to='core.Speaker')),
            ],
        ),
    ]
